nama = input("Nama : ")
nim = input("NIM  : ")
kelas = input("kelas:")
ttl = input("Tempat/Tanggal Lahir: ")
alamat = input("Alamat : ")
hobby = input("hobby : ")
nohp = input("No. HP: ")
print("Nama                 : ", nama)
print("NIM                  : ", nim)
print("Kelas                : ", kelas)
print("Tempat/Tanggal Lahir : ", ttl)
print("Alamat               : ", alamat)
print("Hobby                : ", hobby)
print("No. HP               : ", nohp)

