jari= input()
ting = input()
jari = float(jari)
ting = float(ting)
phi = 3.14
volu = phi*jari*jari*ting
luas = (2*phi*jari*ting)+(2*phi*jari*jari)
kel1 = 2*phi*jari
print("Volume = %.2f" %volu)
print("Luas = %.2f" %luas)
print("Keliling = %.2f" %kel1)
jari1,ting1 = input().split()
jari1 = float(jari1)
ting1 = float(ting1)
volu1 = phi*jari1*jari1*ting
luas1 = (2*phi*jari1*ting1)+(2*phi*jari1*jari1)
kel11 = 2*phi*jari1
print("Volume = %.2f" %volu1)
print("Luas = %.2f" %luas1)
print("Keliling = %.2f" %kel11)
